### ISSUE TITLE
Strings cannot be read from Resources.resx, throws MissingManifestResourceException.

### ISSUE THREAD

**Issue by LeeDawsonUK** [kanisimoff/PluralizeService.Core#7]
To replicate, set `culture` to null in the PluralizationProvider and run the tests. You should get ArgumentNullException, but I get this:

> System.Resources.MissingManifestResourceException: Could not find the resource "PluralizationService.Properties.Resources.resources" among the resources "PluralizeService.Core.Properties.Resources.resources" embedded in the assembly "PluralizeService.Core", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
>   Stack Trace: 
>     ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
>     ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
>     ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>     ResourceManager.GetString(String name, CultureInfo culture)
>     Resources.get_Guard_ArgNullOrEmpty()
>     Guard.ThrowIfNullOrEmpty(String argValue, String argName)
>     DefaultPluralizationApi.IsPlural(String word, CultureInfo culture)
>     PluralizationProvider.IsPlural(String word)
> 

It sounds like the same issue as described in [this SO post.](https://stackoverflow.com/questions/1327692/what-does-missingmanifestresourceexception-mean-and-how-to-fix-it).

### Cause

Automatic inclusion of embedded resources includes the project's default namespace (PluralizeService.Core) at the root of the fully qualified name, as seen here in ILSpy:

![image](https://user-images.githubusercontent.com/23084469/77826770-484ef580-7109-11ea-80b1-e5b1e4a0ee0c.png)

But in `Resources.Designer.cs`, the Resource Manager is initialised with the "old" namespace of PluralizationService:

```
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluralizationService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
```

### Solutions

1. Disable automatic inclusion of resources, and instead specify it manually in the .csproj where you can override the logical name (described [here](https://stackoverflow.com/a/44271615)). Or:
2. Regenerate the `Resources.designer.cs` so it uses the PluralizeService.Core namespace (described in the earlier SO link).

Option 1 touches fewer files but option 2 might be more correct. I've verified both and am happy to PR the preferred solution.

**Comment by kanisimoff** [comment]
I regenerate resources.designer.cs

**Comment by roa-nyx** [comment]
@kanisimoff that assumes we're using a Visual Studio project. For VS Code users this doesn't work. Also as far as I can see my project doesn't have a resources.resx at all. Could we maybe support projects that don't have any resources?
